// Generated by Genetic Drift Simulator
<!DOCTYPE html>
<html lang="en">
<head>
  <title><?=$this->e($title)?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css" />
  <?php if ($this->section('header')): ?>
    <?=$this->section('header')?>
  <?php endif ?>
</head>
<body>
  <div class="container">
    <?=$this->section('content')?>
  </div>
  <?php if ($this->section('footer')): ?>
    <?=$this->section('footer')?>
  <?php endif ?>
</body>
</html>
